# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/kccat6/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/kccat6/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/kccat6/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/kccat6/proprietary/bin/ks:system/bin/ks \
    vendor/samsung/kccat6/proprietary/bin/mdm_helper:system/bin/mdm_helper \
    vendor/samsung/kccat6/proprietary/bin/mdm_helper_proxy:system/bin/mdm_helper_proxy \
    vendor/samsung/kccat6/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/kccat6/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/kccat6/proprietary/bin/radish:system/bin/radish \
    vendor/samsung/kccat6/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/kccat6/proprietary/bin/rmnetcli:system/bin/rmnetcli \
    vendor/samsung/kccat6/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/samsung/kccat6/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/kccat6/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/kccat6/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/samsung/kccat6/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/kccat6/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/kccat6/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/kccat6/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so
